import smtplib 
import random
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders 
from gtts import gTTS
from pydub import AudioSegment
from pydub.playback import play
   
image_to_description = {
    "mewithfriends.jpg": "Hanging out with friends today! Tagged: @johnsmith and @janedoe on 10/20/2019 in San Francisco, CA",
    "puppy.jpg": "Happy 1st birthday to my furry friend! on  01/14/2017 in New York, NY",
    "workout.jpg": "Just finished a 3.11 mile run! on 04/17/2014 in San Francisco, CA",
    "graduation.jpg": "Graduated from UCLA! Tagged: @UCLA, @freddy35459, @alexaroberts on 06/18/2019 in Los Angeles, CA",
    "beach_sunset.jpg": "Watching the sunset at the beach. Beautiful colors on 07/12/2021 in Miami, FL",
    "hiking_trails.jpg": "Conquered the Rocky Mountain trails! on 09/05/2020 in Denver, CO",
    "birthday_party.jpg": "Celebrating my 30th birthday with the best! Tagged: @emily_jones and @mikeclark on 11/22/2019 in Las Vegas, NV",
    "first_day_school.jpg": "Little Tim's first day at school! So proud! on 09/01/2022 in Austin, TX",
    "home_cooked_meal.jpg": "Mastered my grandma’s lasagna recipe! Delicious! on 03/15/2023 in Chicago, IL",
    "concert_night.jpg": "At the Green Day concert! Live music is unbeatable! Tagged: @concertbuddy on 08/29/2018 in New York, NY",
    "snowman_winter.jpg": "First snowman of the season! on 12/15/2020 in Minneapolis, MN",
    "baby_steps.jpg": "Baby’s first steps! Can't believe how fast they grow! on 05/10/2021 in Columbus, OH",
}

#Generated by GPT
# Sample classification of images based on desired emotions:
mood_to_images = {
    "happy": [
        "mewithfriends.jpg",  # Social gatherings often boost happiness.
        "puppy.jpg",          # Cute animals are a common source of joy.
        "graduation.jpg",     # Celebrating personal achievements can make someone happy.
        "birthday_party.jpg", # Birthday celebrations are typically joyous occasions.
        "concert_night.jpg",  # Music events are often associated with happiness and excitement.
        "baby_steps.jpg",     # Family milestones like a baby's first steps bring happiness.
    ],
    "sad": [
        "puppy.jpg",          # Pets can provide comfort during sad times.
        "first_day_school.jpg", # Parents might feel a bittersweet sadness seeing children grow up.
        "snowman_winter.jpg", # Seasonal activities might remind someone of happier times.
    ],
    "angry": [
        "workout.jpg",        # Physical activity is often sought to channel and alleviate anger.
        "hiking_trails.jpg",  # Engaging with nature can be calming when angry.
    ],
    "stressed": [
        "beach_sunset.jpg",   # Natural scenery, like a beach at sunset, can be calming for stressed individuals.
        "home_cooked_meal.jpg", # Comfort food, or the act of cooking, can be stress-relieving.
        "snowman_winter.jpg", # Creative activities like making a snowman can distract and reduce stress.
    ],
}

mood_messages = {
    "happy": [
        "Keep riding that wave of joy—it's great to see you so upbeat!",
        "Your happiness is contagious! Keep spreading that positive energy around you!",
        "It's wonderful to see you so happy! Keep enjoying every moment to the fullest!",
    ],
    "sad": [
        "Even on a cloudy day, the sun is still shining. Hang in there, and you'll see it soon!",
        "It's okay to feel down—remember, every storm passes and leaves a clear sky.",
        "Sending you a little box of sunshine to brighten your day as you always brighten mine!",
    ],
    "angry": [
        "Take a deep breath and feel the peace flowing in. You've got this!",
        "It's absolutely okay to feel angry, but remember to give yourself the gift of calmness soon.",
        "Imagine your anger as a balloon. Now let it go and watch it disappear into the sky.",
    ],
    "stressed": [
        "Remember to take things one step at a time—you're doing way better than you think!",
        "Deep breaths. You're stronger than your stress. You can conquer anything!",
        "Stress is just the weight of things that matter. Let's find a way to lighten your load."
    ]
}



def send_email(fromaddr, toaddr, body, filename, password):   
    msg = MIMEMultipart() 
    msg['From'] = fromaddr 
    msg['To'] = toaddr 
    msg['Subject'] = "Incoming Message"
    msg.attach(MIMEText(body + " " + image_to_description[filename], 'plain')) 
    attachment = open("images/" + filename, "rb") 
    p = MIMEBase('application', 'octet-stream') 
    p.set_payload((attachment).read()) 
    encoders.encode_base64(p) 
    p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 
    msg.attach(p) 
    s = smtplib.SMTP('smtp.gmail.com', 587) 
    s.starttls() 
    s.login(fromaddr, password) 
    text = msg.as_string() 
    s.sendmail(fromaddr, toaddr, text) 
    s.quit() 

def select_image(mood):
    images = mood_to_images[mood]
    return random.choice(images)

def text_to_speech(text, output_file, lang='en'):
    tts = gTTS(text=text, lang=lang)
    tts.save(output_file)
    return output_file

def play_audio(file_path):
    audio = AudioSegment.from_file(file_path)
    play(audio)

def speak_message(mood):
    # Select a random message for the given mood
    message = random.choice(mood_messages[mood])
    # Define the output audio file
    output_file = 'output_message.mp3'
    # Convert the message to speech
    text_to_speech(message, output_file)
    # Play the audio message
    play_audio(output_file)

#For manual testing purposes 
#Mood_in should be the input from the model
mood_in = input("How are you feeling? Choose from 'happy', 'sad', 'angry', 'stressed': ").lower().strip()


file_name_from_input = select_image(mood_in)


# send_email("iddhomies@gmail.com", "zjpakin@gmail.com", "MoodHelper has tuned into your " + mood_in + " mood. Here's a picture to brighten your day!", file_name_from_input, open('gmail_password.key', 'r').read().strip())
send_email("iddhomies@gmail.com", "zpakin@hpeprint.com", "MoodHelper has tuned into your " + mood_in + " mood. Here's a picture to brighten your day!", file_name_from_input, open('gmail_password.key', 'r').read().strip())
speak_message(mood_in)